# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Solar Control Site
    url: https://www.solar-control.tech
  - name: Solar Control Viber Bot
    url: $VIBER
    expectedStatusCodes:
      - 500
  - name: Solar Control Cloud
    url: $API_SOLCON
    __dangerous__insecure: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.solar-control.tech
  # baseUrl: /your-repo-name
  logoUrl: https://www.solar-control.tech/assets/images/logo.svg
  name: Solar Control Uptime
  introTitle: "**Solar Control Uptime** - це сторінка, що показує стан основних сервісів компанії Solar Control"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
